### ISSUE TITLE
cstruct.to_bigarray is not equal after going through io_page

### ISSUE THREAD

**Issue by hannesm** [mirage/io-page#17]
I encounter to run in a failed assertion (line 20) in https://github.com/hannesm/test -- which reproduces the code ocaml-crunch contains for reading data from its key-value store.

a string is put into an io_page, and a cstruct of the given string length is exposed -- the cstruct is not equal (using to_bigarray) to a cstruct produced by of_string of the initial string...

this problem occurs here on FreeBSD (seems to work fine on linux) with io-page 1.4.0 and 1.2.0 at least...

**Comment by yallop** [comment]
This looks like an element type incompatibility issue.  The stub [creates a uint8 array](https://github.com/mirage/io-page/blob/f56c53faba2e6e8598285609fc49327bdf0cea2a/lib/stub_alloc_pages.c#L55):

```ocaml
caml_ba_alloc_dims(CAML_BA_UINT8 | CAML_BA_C_LAYOUT | CAML_BA_MANAGED, 1, block, len)
```
but the [declared type is a char array](https://github.com/mirage/io-page/blob/master/lib/io_page.ml#L19):

```ocaml
type t = (char, int8_unsigned_elt, c_layout) Array1.t
```

**Comment by yallop** [comment]
In OCaml 4.01 the char and uint8 type representations were [equal](https://github.com/ocaml/ocaml/blob/4.01.0/otherlibs/bigarray/bigarray.ml#L48); in 4.02 they're [distinct](https://github.com/ocaml/ocaml/blob/64ee2135ded944021f9e0bbf3e1dc65fcd60b6c9/otherlibs/bigarray/bigarray.mli#L73-L86).

**Comment by hannesm** [comment]
@yallop thanks for the analysis - switching the allocator to `CAML_BA_CHAR` solves the problem.

I wonder whether io-page and cstruct should really use character arrays, and not uint8 arrays instead. Any opinions on that? (and is there a performance-argument to choose one over the other)?

Happy to submit pull requests for either direction...
