### ISSUE TITLE
deprecate the library

### ISSUE THREAD

**Issue by samoht** [mirage/io-page#19]
We should deprecate the library. There is no good reasons to expose io-pages to code which is not a device driver.

@djs55 do you think that's doable?

**Comment by djs55** [comment]
I think we could deprecate io-page and use aligned pages inside drivers only, but it would cause us to sometimes have a data copy on the driver input, to re-align the data. I suppose we could

- deprecate `Io_page.{t,get}` etc
- use `Cstruct.t` everywhere
- provide convenience APIs to allocate aligned `Cstruct.t`s which wouldn't need to be (always) copied? This would allow some special-case apps to avoid the copy.

I guess quite a few modules which consume `Cstruct.t` already have to copy them for other reasons. This happens with Linux too, when a block write happens over NFS, the kernel has to copy the VM's page into private buffers to make sure it can perform a later TCP retransmit. I wonder if we need to think of new API conventions to handle buffer ownership?

**Comment by samoht** [comment]
We discussed about that with @pqwy and @hannesm and I think a good way to go is:
1. to remove all the function which are not `create` and `to_cstruct` in the Io_page API and see what we break (we suspect: not much)
2. move the remaining `Io_page` module in `Cstruct` 
3. remove the module and add an optional argument to `Cstruct.create` to have page-aligned buffers

we can pick either 2. or 3., whichever is the most convenient (I think it's still useful in the device drivers to have an abstract type for page aligned buffer)

**Comment by samoht** [comment]
Regarding buffer ownership: https://github.com/mirage/mirage-net-xen/pull/17 already shown that we didn't loose anything (actually we gain performance *and* safety) by copying the pages in the device drivers and not exposing the `Io_page.t` to the users. Maybe we should do the same thing for storage devices.

**Comment by yomimono** [comment]
@samoht, @pqwy , @djs55, @hannesm - does the "way to move forward" mentioned here:

> to remove all the function which are not create and to_cstruct in the Io_page API and see what we break (we suspect: not much)
> move the remaining Io_page module in Cstruct
> remove the module and add an optional argument to Cstruct.create to have page-aligned buffers
> we can pick either 2. or 3., whichever is the most convenient (I think it's still useful in the device drivers to have an abstract type for page aligned buffer)

still seem reasonable to you?  As described, it seems like a good candidate for inclusion in 3.0.

**Comment by samoht** [comment]
yes, still looks like a good idea. @yallop might have some opinions too :-)

**Comment by avsm** [comment]
I still remain extremely wary of losing the page-aligned property on buffer writes, since it absolutely forces every single consumer of the library to do a data copy in the future, with little chance of ever removing it.

The single Xen datapoint in mirage/mirage-net-xen#17 is not very compelling or broad, given the rich history of changing performance measurements for page flipping vs copying on Xen itself over the course of just a decade...

**Comment by cfcs** [comment]
Are we still looking at deprecating the library?

**Comment by avsm** [comment]
No, I think we'll come back to this as part of a wider design discussion around the I/O stack in Mirage. Right now Io_page is very much not deprecated.
