### ISSUE TITLE
Appveyor CI broken due to missing tool "jq"

### ISSUE THREAD

**Issue by cfcs** [mirage/io-page#40]
see: https://ci.appveyor.com/project/djs55/io-page/build/1.0.29#L437

I am not sure why it tries to install `my-package`, or who decided `jq` was the best way to parse the output, but the current state is not working anyway.

**Comment by samoht** [comment]
The Appveyor scripts needs to be updated to use the [new upstream](https://github.com/ocaml/ocaml-ci-scripts/blob/master/appveyor.yml).

**Comment by djs55** [comment]
Fixed by #43
